### ISSUE TITLE
How do we install 12.2?

### ISSUE THREAD

**Issue by asb2018** [oravirt/ansible-oracle#113]
By default it is installing version 18. What changes do we need to make to install 12.2?
Thank you.

**Comment by asb2018** [comment]
Which files need to be modified to install 12.2 ?

**Comment by oravirt** [comment]
You need to change the following:
You can call the key (`12201-base`) whatever you want as long as it is the same across the other dictionaries, this is just an example. 
The `<--- #####` markers shows you what needs to be consistent across the dictionaries in terms of `ORACLE_HOME`
```
db_homes_config:
  12201-base:        <--- #####
    home: db1-base
    version: 12.2.0.1
    edition: EE

db_homes_installed:
     - home: 12201-base    <--- #####
       apply_patches: False
       state: present
```
and, then you need to adjust `oracle_databases` accordingly to use the correct home:

```
oracle_databases: 
        - home: 12201-base   <--- #####
          oracle_db_name: orcl
          ....
```
and if you want to have pdbs created this needs to match as well.


```
oracle_pdbs:
  - home: 12201-base    <--- #####
    pdb_name: orclpdb
    cdb: orcl
```

**Comment by asb2018** [comment]
Thank you for quick response. After adding , do we need to give any version number 
ansible-playbook dbcreation.yml

How does it pick non default version?

**Comment by oravirt** [comment]
Well, this is decided based on your config. 
Ansible will loop through the dictionary called `db_homes_installed` and install all homes that have `state: present`
e.g

```
db_homes_config:
  12201-base:        <--- 12.2.0.1
    home: db1-base
    version: 12.2.0.1
    edition: EE
  12102-base:        <--- 12.1.0.2
    home: db1-base
    version: 12.1.0.2
    edition: EE

db_homes_installed:
     - home: 12201-base    <--- 12.2.0.1
       apply_patches: False
       state: present
     - home: 12102-base    <--- 12.1.0.2
       apply_patches: False
       state: present
```
Then it's up to you to make sure the DB you want to create is based out of the correct home
(NOTE: This is just a subset of keys available to you in `oracle_databases`
```
oracle_databases: 
        - home: 12201-base   <--- 12.2.0.1
          oracle_db_name: db122
          ....
          state: present
        - home: 12102-base   <--- 12.1.0.2
          oracle_db_name: db121
          ....
          state: present
```

So you don't pass any specific version numbers to the playbook.
