### ISSUE TITLE
dbhome confusion

### ISSUE THREAD

**Issue by stelb** [oravirt/ansible-oracle#122]
i tried to install two databases with different versions and got this error

TASK [oradb-manage-db : manage-db | create/manage database] ***************************
fatal: [db01n2.dev.int.nexinto.com]: FAILED! => {"changed": false, "msg": "Database TEST already exists in a different home. Stdout -> PRCD-1229 : An attempt to access configuration of database TEST was rejected because its version 12.1.0.2.0 differs from the program version 12.2.0.1.0. Instead run the program from /www/oracle/12.1.0.2/ee.\n"}

i removed the second database from my config and still the same error, it only succeeded after removal of the second dbhome.

ansible-oracle ff2604cc6767e24c395139e7a3f83e4bbcecc1da
modules: 23510bf00465ff8d508ee62b5d426463bb4ab47c

**Comment by oravirt** [comment]
So, you had 2 homes: 12.2.0.1 & 12.1.0.2 and the first database was created in the 12.1.0.2 home?
Is that correct?

**Comment by stelb** [comment]
here it is:
```
db_homes_config:
  ee-12.1.0.2:
     home: ee
     version: 12.1.0.2
     edition: EE
  se2-12.2.0.1:
     home: se2
     version: 12.2.0.1
     edition: SE2

db_homes_installed:
     - home: ee-12.1.0.2
       apply_patches: False
       state: present
     - home: se2-12.2.0.1
       apply_patches: False
       state: present
```

**Comment by stelb** [comment]
and yes, the first db created was 12.1.0.2

```
---
oracle_databases:
      - home: ee-12.1.0.2
        oracle_db_name: TEST
        oracle_db_type: SI
        is_container: True
        storage_type: ASM
        oracle_db_mem_totalmb: 4096
        oracle_database_type: MULTIPURPOSE
        redolog_size: 100M
        datafile_dest: '+SI_DATA'
        recoveryfile_dest: '+SI_DATA'
        archivelog: false
        flashback: false
        force_logging: false
        state: present
```
