### ISSUE TITLE
oradb-manage-db failed

### ISSUE THREAD

**Issue by dddd45** [oravirt/ansible-oracle#130]
Hi

I try to install and create Oracle database 18c and it failed with this below error.

I just download ansible-oracle-master.zip and ansible-oracle-module.zip (extracted to ansible-oracle-master/library) and place Oracle 18c software to /tmp and then run the single-instance-db-on-fs.yml (already configured hostname).

My platform is Oracle Linux 7.5

**TASK [oradb-manage-db : manage-db | create/manage database] ********************
fatal: [anstest]: FAILED! => {"changed": false, "cmd": "/u01/app/oracle/12.2.0.1/db1-base/bin/sqlplus -V", "msg": "[Errno 2] No such file or directory", "rc": 2}**

Why it would create by using 12.2 version? How can I fix this?

Thanks

**Comment by oravirt** [comment]
Hi - I know what the problem is. I’ll fix this asap

**Comment by dddd45** [comment]
Thank you

**Comment by oravirt** [comment]
Should be fixed with 98cc3175d541109d5d4cd84a253efafe2f24bd80

**Comment by dddd45** [comment]
Hi,

I tried running again and the issue has been solved. Thank for that.

but I got new issue below.
**TASK [oradb-manage-db : manage-db | create/manage database] ********************
fatal: [anstest]: FAILED! => {"changed": false, "msg": "Could not connect to database - ORA-12541: TNS:no listener, connect descriptor: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ansible-srs)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)))"}**

I checked my /etc/hosts and saw
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
**192.168.122.1 anstest anstest**


My ifconfig:
**enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.101  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a04e:5ebd:6ed0:dce5  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:77:4a:e9  txqueuelen 1000  (Ethernet)
        RX packets 6635  bytes 5277409 (5.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1743  bytes 144959 (141.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 1719499  bytes 13731524274 (12.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1719499  bytes 13731524274 (12.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:ae:d8:4f  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0**

I configured the /etc/hosts as below before running the playbook I swear.
192.168.1.101 anstest anstest

Why do my /etc/hosts have configured to 192.168.122.1 after running the playbook? Is it relate to the issue of failed above?

Thank you

**Comment by Rendanic** [comment]
I think that this is related to a missing listener configuration.
2 solutions:
- start a listerner and restart the playbook
- configura a listener in oracle_databases and other variables for the listener

I always configure dedicated listener in my setups, because it will create a lot of issues when we try to find solutions for default configurations without a dedicated listenerdefinition.

Example for my 12.2 configuration: (oracle_databases includes only the mandatory variables for a listener definition!)
```
oracle_databases:
      - home: 12201-latest
        oracle_db_name: testdb
        listener_name: LISTENER
        listener_port: 1521

oracle_listeners_config:
   LISTENER:
        home: 12201-latest
        address:
          - host: "{{ansible_hostname}}"
            protocol: TCP
            port: 1521

listener_installed:
      - home: 12201-latest
        listener_name: LISTENER
        state: present
```

**Comment by dddd45** [comment]
How can I do that?  Sorry I am beginner in Ansible.

**Comment by dddd45** [comment]
Hi
I have tried to uninstall and re-install Oracle Linux 7.5 with Ansible again. I removed the virbr0 interface first before running Ansible playbook for installing and creating database and it worked!!!.

Just a question, how to delete database? I tried delete-db.yml and it resulted this below error:
**[ansible@anstest ansible-oracle-master]$ ansible-playbook delete-db.yml

PLAY [Delete Database(s)] *******************************************************

TASK [Gathering Facts] **********************************************************
ok: [anstest]
ERROR! 'configure_cluster' is undefined**


Thanks

**Comment by oravirt** [comment]
1. Use` manage-db.yml `instead. I'll remove `delete-db.yml,` it's an old version.
2. The state of the database in question needs to be set to absent (`state: absent`)
e.g
```
oracle_databases:
   - home: 12102-base
     oracle_db_name: db121
     .......
     state: absent  <--- THIS
```
