### ISSUE TITLE
oradb-manage-db listener_details creates invalid listener.ora when there's multiple databases defined

### ISSUE THREAD

**Issue by chrisbrookes** [oravirt/ansible-oracle#152]
- Ansible 2.7.6
- Oracle 18.3

In a configuration where there is one listener with multiple DB instances (tested with Oracle 18.3 only), the generated `/u01/app/oracle/18.3.0.0/db1-base/network/admin/listener.ora` has bad syntax and Oracle complains when trying to start it:
```
[oracle@centosora1 ~]$ lsnrctl start LISTENER18
LSNRCTL for Linux: Version 18.0.0.0.0 - Production on 28-JAN-2019 11:04:22
Copyright (c) 1991, 2018, Oracle.  All rights reserved.
Starting /u01/app/oracle/18.3.0.0/db1-base/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 18.0.0.0.0 - Production
System parameter file is /u01/app/oracle/18.3.0.0/db1-base/network/admin/listener.ora
Log messages written to /u01/app/oracle/diag/tnslsnr/centosora1/listener18/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=centosora1)(PORT=1521)))
TNS-01155: Incorrectly specified SID_LIST_LISTENER18 parameter in LISTENER.ORA
 NL-00303: syntax error in NV string

Listener failed to start. See the error message(s) above...
```

Example config:
```yaml
db_homes_config:
  18300-base:
    home: db1-base
    version: 18.3.0.0
    edition: EE

db_homes_installed:
- home: 18300-base
  apply_patches: False
  state: present

oracle_listeners_config:
  LISTENER18:
    home: 18300-base
    address:
    - host: "{{ansible_hostname}}"
      protocol: TCP
      port: 1521

listener_installed:
- home: 18300-base
  listener_name: LISTENER18
  state: present

oracle_databases:     
- home: 18300-base 
  oracle_db_name: orcl18
  oracle_db_type: SI
  is_container: False
  #  is_container: true
  storage_type: FS
  oracle_db_mem_totalmb: 600
  oracle_database_type: MULTIPURPOSE  
  redolog_size: 100M
  redolog_groups: 3
  archivelog: False
  flashback: False
  force_logging: True
  listener_name: LISTENER18
  listener_port: 1521
  state: present
  init_parameters:
    - { name: recyclebin, value: "OFF", state: present, scope: spfile }

# a 2nd db
- home: 18300-base 
  oracle_db_name: orcl18alt1
# ...
# a third db
- home: 18300-base 
  oracle_db_name: orcl18alt2
# ...
```

One instance generates this listener.ora (valid):
```
# BEGIN Ansible managed for  LISTENER18

# do not edit the configuration manually.
# The execution of ansible-oracle automatically replace all manual changes!

LISTENER18 =
  (DESCRIPTION =
    (ADDRESS_LIST=
      (ADDRESS = (PROTOCOL = TCP)(HOST = centosora1)(PORT = 1521))
    )
  )

SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
  )
# END Ansible managed for  LISTENER18
```

3 listeners give this (2 is the same has things twice instead of thrice):
```
# BEGIN Ansible managed for  LISTENER18

# do not edit the configuration manually.
# The execution of ansible-oracle automatically replace all manual changes!

LISTENER18 =
  (DESCRIPTION =
    (ADDRESS_LIST=
      (ADDRESS = (PROTOCOL = TCP)(HOST = centosora1)(PORT = 1521))
    )
  )

SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
    (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
      (GLOBAL_DBNAME = orcl18alt_DGMGRL)
    )
    (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
      (GLOBAL_DBNAME = orcl18alt2_DGMGRL)
    )
  )

SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
    (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
      (GLOBAL_DBNAME = orcl18alt_DGMGRL)
    )
    (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
      (GLOBAL_DBNAME = orcl18alt2_DGMGRL)
    )
  )

SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
    (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
      (GLOBAL_DBNAME = orcl18alt_DGMGRL)
    )
    (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
      (GLOBAL_DBNAME = orcl18alt2_DGMGRL)
    )
  )
# END Ansible managed for  LISTENER18
```

1. There should only be one `SID_LIST_LISTENER18` section
1. There are spurious `(SID_LIST =` in the middle of a valid `(SID_LIST =` section. This is the problem that really breaks it

I tried a workaround on the [listener_details.j2](https://github.com/oravirt/ansible-oracle/blob/master/roles/oradb-manage-db/templates/listener_details.j2) template that fixes `#2`, ~line 43:
```jinja
{% if loop.index == 1 %}
  (SID_LIST =
{% endif %}
```
Which works ok, but no idea if this should be a proper fix (and it doesn't fix `#1`)

**Comment by oravirt** [comment]
@Rendanic Would you mind taking a look?

**Comment by Rendanic** [comment]
I need some time to analyze the problem. Most test were done with 1 Instance per listener but I am suprissed, that this was not detected by other DBAs, because the project is used for some environments at our customers. Maybe this is a combination I didn't tested before. :-(

**Comment by Rendanic** [comment]
> There should only be one SID_LIST_LISTENER18 section

The SID_LIST_LISTENER is created with a loop over '`listener_installed:`'. I added another database to oreacle_databases and can't see the addional `SID_LIST_LISTENER`.
Could you create a report with ansible-inventory and check if the variable '`listener_installed:`' shows more then 1 element in the list?

> There are spurious (SID_LIST = in the middle of a valid (SID_LIST = section.

 This is really a bug and I can reproduce the problem.

**Comment by chrisbrookes** [comment]
Just one listener_installed defined:
```
$ ansible-inventory --host=centosora1 | grep -A 6 listener_installed

    "listener_installed": [
        {
            "home": "18300-base", 
            "listener_name": "LISTENER18", 
            "state": "present"
        }
    ], 



```

**Comment by chrisbrookes** [comment]
The only way I can "fix" the multiple SID_LIST_LISTENER is to put an if that checks the loop index around the `SID_LIST_{{ lsnrinst.listener_name }} =` logic (line below marked with `multiple SID_LIST_LISTENER issue workaround`:

```
{# config_sid_list is used as a helper. jinja2 doesn't allow the exposing of variables from inside a loop to outside before version 2.10! #}
{%- set config_sid_list = 0 %}
{# The following loop is executed only once for the header 'SID_LIST_... #}
{%- for testsid in oracle_databases if testsid.listener_name is defined and testsid.listener_name == lsnrinst.listener_name and config_sid_list == 0 %}
  {%- set config_sid_list =  1 %}
{% if loop.index == 1 %}{# multiple SID_LIST_LISTENER issue workaround #}
SID_LIST_{{ lsnrinst.listener_name }} =
{# loop over oracle_database when testsid.listener_name was found for lsnrinst.listener_name #}
  {%- for sid in oracle_databases if sid.listener_name is defined and sid.listener_name == lsnrinst.listener_name %}
{%- set sid_name = sid.oracle_db_instance_name | default(sid.oracle_db_name) %}
{%- set sid_name_dgmgrl = sid.oracle_db_unique_name | default(sid.oracle_db_name) %}
{% if loop.index == 1 %}{# workaround for SID_LIST issue #}
  (SID_LIST =
{% endif %}
    (SID_DESC =
    {% if db_homes_config[sid.home]['oracle_home'] is defined %}
  (ORACLE_HOME = {{db_homes_config[sid.home]['oracle_home']}})
    {% else %}
  (ORACLE_HOME = {{oracle_base}}/{{db_homes_config[sid.home]['version']}}/{{db_homes_config[sid.home]['home']}})
    {% endif %}
  (SID_NAME = {{ sid_name }})
    )
{# added for compatibility against Oracle 11.2#}
    (SID_DESC =
    {% if db_homes_config[sid.home]['oracle_home'] is defined %}
  (ORACLE_HOME = {{db_homes_config[sid.home]['oracle_home']}})
    {% else %}
  (ORACLE_HOME = {{oracle_base}}/{{db_homes_config[sid.home]['version']}}/{{db_homes_config[sid.home]['home']}})
    {% endif %}
  (SID_NAME = {{ sid_name }})
      (GLOBAL_DBNAME = {{ sid_name_dgmgrl }}_DGMGRL)
    )
  {% endfor %}
)
{% endif %}
{% endfor %}
```
Like the other workaround I'm not sure if this would work in all combinations of DBs + listeners, I'm admittedly just hacking it around.

I'm a bit confused what the `config_sid_list` is doing, since after writing out the values in each loop iteration, the values seem to reset, e.g. with these comments inserted:

```
{%- for testsid in oracle_databases if testsid.listener_name is defined and testsid.listener_name == lsnrinst.listener_name and config_sid_list == 0 %}
# config_sid_list(1): {{ config_sid_list }} ({{ testsid.oracle_db_name }})
  {%- set config_sid_list =  1 %}

# config_sid_list(2): {{ config_sid_list }} ({{ testsid.oracle_db_name }})
SID_LIST_{{ lsnrinst.listener_name }} =
```



Generates in the file as:
```
# config_sid_list(1): 0 (orcl18)
# config_sid_list(2): 1 (orcl18)
SID_LIST_LISTENER18 =
[...]
# config_sid_list(1): 0 (orcl18alt)
# config_sid_list(2): 1 (orcl18alt)
SID_LIST_LISTENER18 =
[...]
```
Is `config_sid_list` an attempt to stop the iteration?

**Comment by Rendanic** [comment]
I tried different configurations but I am not able to reproduce the problem with `SID_LIST_LISTENER18`.
It's better to find the root cause of this issue before we implement a work arround. Maybe we hit another problem at a different point and all is related to the same issue.

Could you show us the following variables from ansible-inventory:
- oracle_databases
- db_homes_config
- db_homes_installed
- oracle_listeners_config
- listener_installed

**Comment by Rendanic** [comment]
I did another test with the following configuration without the SID_LIST_ problem.
I executed the role `oradb-manage-db` with `--tags=listener2`.

ansible 2.7.7

```
db_homes_config:
  18300-base:
    home: db1-base
    version: 18.3.0.0
    edition: EE

db_homes_installed:
- home: 18300-base
  apply_patches: False
  state: present

oracle_listeners_config:
  LISTENER18:
    home: 18300-base
    address:
    - host: "{{ansible_hostname}}"
      protocol: TCP
      port: 1521

listener_installed:
- home: 18300-base
  listener_name: LISTENER18
  state: present


oracle_databases:
- home: 18300-base
  oracle_db_name: orcl18
  oracle_db_type: SI
  is_container: False
  #  is_container: true
  storage_type: FS
  oracle_db_mem_totalmb: 600
  oracle_database_type: MULTIPURPOSE
  redolog_size: 100M
  redolog_groups: 3
  archivelog: False
  flashback: False
  force_logging: True
  listener_name: LISTENER18
  listener_port: 1521
  state: present
  init_parameters:
    - { name: recyclebin, value: "OFF", state: present, scope: spfile }

# a 2nd db
- home: 18300-base
  oracle_db_name: orcl18alt1
  listener_name: LISTENER18
# ...
# a third db
- home: 18300-base
  oracle_db_name: orcl18alt2
  listener_name: LISTENER18

````

listener.ora:
```

LISTENER18 =
  (DESCRIPTION =
    (ADDRESS_LIST=
      (ADDRESS = (PROTOCOL = TCP)(HOST = oradg01)(PORT = 1521))
    )
  )

SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
      (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt1)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt1)
      (GLOBAL_DBNAME = orcl18alt1_DGMGRL)
    )
      (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt2)
      (GLOBAL_DBNAME = orcl18alt2_DGMGRL)
    )
```

**Comment by chrisbrookes** [comment]
Thanks for that. I will update to this and see if I can still reproduce the multiple SID_LIST_LISTENER18 problem. If so I'll document the variables I'm using.

**Comment by chrisbrookes** [comment]
Reproduced it again with updated changes.

My var config (in inventory):
```yaml
db_homes_config:
  18300-base:
    home: db1-base
    version: 18.3.0.0
    edition: EE

db_homes_installed:
- home: 18300-base
  apply_patches: False
  state: present

#---------------------------------------------------------------------------------------------------------------------
oracle_sw_image_db:
- { filename: LINUX.X64_180000_db_home.zip, version: 18.3.0.0, creates: 'install/.img.bin' }
- { filename: linuxx64_12201_database.zip, version: 12.2.0.1, creates: 'database/runInstaller' }
- { filename: linuxamd64_12102_database_1of2.zip, version: 12.1.0.2, creates: 'database/stage/sizes/oracle.server.Custom.sizes.properties' }
- { filename: linuxamd64_12102_database_2of2.zip, version: 12.1.0.2, creates: 'database/install/.oui' }
- { filename: p13390677_112040_Linux-x86-64_1of2.zip, version: 11.2.0.4, creates: 'database/install/resource/cons_zh_TW.nls' }
- { filename: p13390677_112040_Linux-x86-64_2of2.zip, version: 11.2.0.4, creates: 'database/stage/Components/oracle.rdbms/11.2.0.4.0/1/DataFiles/filegroup18.jar' }

#---------------------------------------------------------------------------------------------------------------------
dbpasswords:
  orcl18:
    sys: Oraclesecret
    system: Oraclesecret
    appuser1: pass # todo: can change this with the update_password "always" setting, but task is not marked as changed: https://github.com/oravirt/ansible-oracle-modules/issues/87
  orcl18alt:
    sys: Oraclesecret
    system: Oraclesecret
    appuser1: Oraclesecret
  orcl18alt2:
    sys: Oraclesecret
    system: Oraclesecret

#---------------------------------------------------------------------------------------------------------------------
# Databases
oracle_databases:                                      # Dictionary describing the databases to be installed
- home: 18300-base                                     # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
  oracle_db_name: orcl18                               # Database name
  oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
  is_container: False                                  # (true/false) Is the database a container database
#  is_container: true                                  # (true/false) Is the database a container database
#  pdb_prefix: pdb # todo: this needed if I'm not using pdbs?
#  num_pdbs: 2 # todo: this needed if I'm not using pdbs?
  storage_type: FS                                     # Database storage to be used. ASM or FS.
  oracle_db_mem_totalmb: 768                           # Amount of RAM to be used for SGA + PGA
  oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
  redolog_size: 100M
  redolog_groups: 3
  archivelog: False
  flashback: False
  force_logging: True
  listener_name: LISTENER18
  listener_port: 1521
  state: present                                        # present | absent
  tablespaces:
    - { name: users, size: 50M, datafile: ['/u01/oradata/ORCL18/users01.dbf'], autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
    - { name: mytemp, size: 50M, datafile: ['/u01/oradata/ORCL18/mytemp01.dbf'], autoextend: false , next: 5M, maxsize: 500M, content: temp, state: present }
    - {
        name: testy,
        size: 10M,
        datafile: ['/u01/oradata/ORCL18/test01.dbf', '/u01/oradata/ORCL18/test02.dbf', '/u01/oradata/ORCL18/test03.dbf'],
        autoextend: true,
        next: 5M,
        maxsize: 500M,
        content: permanent,
        state: present
      }
  init_parameters:
    - { name: recyclebin, value: "OFF", state: present, scope: spfile }
  users:
    - schema: appuser1
      update_password: "always"
      default_tablespace: testy
      default_temp_tablespace: mytemp
      grants:
      - approle1
      state: present
  roles:
    - name: approle1
      grants:
        - connect
        - create database link
        - create procedure
        - create sequence
        - create synonym
        - create table
        - create trigger
        - create type
        - create view
      object_privs:
        - execute:sys.dbms_lock
        - select:sys.dba_pending_transactions
      state: present
#---------------------------------------------------------------------------------------------------------------------
# another db instance
#
- home: 18300-base                                     # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
  oracle_db_name: orcl18alt                             # Database name
  oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
  is_container: False                                  # (true/false) Is the database a container database
  storage_type: FS                                     # Database storage to be used. ASM or FS.
  oracle_db_mem_totalmb: 768                           # Amount of RAM to be used for SGA + PGA
  oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
  redolog_size: 100M
  redolog_groups: 3
  archivelog: False
  flashback: False
  force_logging: True
  listener_name: LISTENER18
  listener_port: 1521
  state: present                                        # present | absent
  tablespaces:
    - { name: users, size: 50M, datafile: ['/u01/oradata/ORCL18ALT/users01.dbf'], autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
    - {
      name: testy,
      size: 10M,
      datafile: ['/u01/oradata/ORCL18ALT/test01.dbf'],
      autoextend: true,
      next: 5M,
      maxsize: 500M,
      content: permanent,
      state: present
    }
  init_parameters:
    - { name: recyclebin, value: "OFF", state: present, scope: spfile }

#---------------------------------------------------------------------------------------------------------------------
# Listeners
#
oracle_listeners_config:
  LISTENER18:
    home: 18300-base
    address:
    - host: "{{ansible_hostname}}"
      protocol: TCP
      port: 1521

listener_installed:
- home: 18300-base
  listener_name: LISTENER18
  state: present
```
My playbook:
```yaml
#!/usr/bin/env ansible-playbook

# Test for new db scripts
#
#
# ansible-playbook tmp-new-db-test.yml -e hostgroup=centosora1 -i inventory/test --user=root
---

- name: Control get ansible oracle from git
  hosts: localhost
  pre_tasks:
  - name: Clone/Pull the ansible-oracle repository
    # Ideally use a version tag, but sometimes it may need to be the commit #.
    git: repo="https://github.com/oravirt/ansible-oracle.git" force=yes accept_hostkey=yes clone=yes
      version="9122c57e23726dee338aeeaaa3709b6b5085b526" dest="roles-ext/ansible-oracle" recursive=yes track_submodules=no
    tags: ansible-oracle

- name: Host configuration
  hosts: "{{ hostgroup }}"
  become: yes

  roles:
  - ansible-oracle/roles/common
  - ansible-oracle/roles/orahost
  - ansible-oracle/roles/cxoracle
  tags: host

- name: Database Server Installation & Database Creation
  hosts: "{{ hostgroup }}"
  become: yes
  roles:
    - ansible-oracle/roles/oraswdb-install
    - ansible-oracle/roles/oradb-manage-db
  tags: install

- name: Customise database(s) / users etc
  hosts: "{{ hostgroup }}"
  become: yes
  roles:
    - ansible-oracle/roles/oradb-manage-tablespace
    - ansible-oracle/roles/oradb-manage-parameters
    - ansible-oracle/roles/oradb-manage-roles
    - ansible-oracle/roles/oradb-manage-users
    - ansible-oracle/roles/oradb-manage-grants
  tags: customise
  post_tasks:
    - debug: var=oracle_home_db
      with_items: "{{ db_homes_installed }}"
      tags: directoriesdb
```

Gives me a generated listener.ora of:
```
# BEGIN Ansible managed for  LISTENER18

# do not edit the configuration manually.
# The execution of ansible-oracle automatically replace all manual changes!

LISTENER18 =
  (DESCRIPTION =
    (ADDRESS_LIST=
      (ADDRESS = (PROTOCOL = TCP)(HOST = centosora1)(PORT = 1521))
    )
  )

SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
      (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
      (GLOBAL_DBNAME = orcl18alt_DGMGRL)
    )
  
SID_LIST_LISTENER18 =
  (SID_LIST =
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18)
      (GLOBAL_DBNAME = orcl18_DGMGRL)
    )
      (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
    )
    (SID_DESC =
      (ORACLE_HOME = /u01/app/oracle/18.3.0.0/db1-base)
      (SID_NAME = orcl18alt)
      (GLOBAL_DBNAME = orcl18alt_DGMGRL)
    )
  )
# END Ansible managed for  LISTENER18
```
