### ISSUE TITLE
ORACLE_HOME confusion

### ISSUE THREAD

**Issue by g10chy** [oravirt/ansible-oracle#161]
How can I get the software to install down different path? e.g. /u01/app/oracle/product/18.3.0.0/dbhome1

It is currently going /u01/app/oracle/18.3.0.0/dbhome1 but can't see where I need to customise to add the product

Thanks

**Comment by langesven** [comment]
You should be able to configure that via setting the `oracle_home` property of a database.
```
db_homes_config:
  18300-base:
    home: dbhome1
    oracle_home: "{{ oracle_base }}/{{ product_name }}/18.3.0.0/dbhome1"
    version: 18.3.0.0
    edition: EE
```
