### ISSUE TITLE
oracle_pdbs - non-default listener port

### ISSUE THREAD

**Issue by g10chy** [oravirt/ansible-oracle#164]
oradb-manage-tablespaces was defaulting to port 1521.
As I am not using default 1521, I have had to add listener_port option to the oracle_pbs dictionary.

```
oracle_pdbs:
  - home: 18300-base
    pdb_name: orclpdb1
    datafile_dest: /u01/oradata/
    cdb: orclcdb
    listener_port: 1621
```

As CDB is referenced in oracle_pdb, could we not take listener_port from oracle_databases dictionary rather than having to maintain twice?

**Comment by Rendanic** [comment]
You can set the following variable to set a default port for CDB and PDB Listener on a host:
`listener_port: 1521`

Another way is using anchors in the Inventory:
```
oracle_databases:
  - oracle_db_name: &oracle_db_name DB1
    listener_port: &cdb_listener_port 1521

oracle_pdbs:
  - home: *db_config_home
    listener_port: *cdb_listener_port
    cdb: *oracle_db_name
    pdb_name: ORCLPDB

```
Full example is here: https://github.com/opitzconsulting/ansible-oracle-inventory/blob/main/inventory/dbfs/group_vars/dbfs/database_DB1.yml
