### ISSUE TITLE
better detection in Check if database is already created

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#17]
The current method has issues in RAC environments. 
I think the following logic should work:
- no change for current logic with register: checkdbexist
  There is no need to change the other tasks for the new logic.
- add another when to current task
  The existing task gets another when clause and only applies to installations without Oracle Restart / GI.
  Also change the search for the SID to '^item.oracle_db_name:oracle_home:'. 
  => We really find the right entry in oratab for the ORACLE_SID
- add a new task like the existing Check if database is already created
  This task is only for Oracle Restart / GI. We could get the state of the database with srvctl status database -d <item.oracle_db_name> and return '1' when a database was found on the system.
  This is compatible against the current logic and is easy to add without changing a lot of tasks.

What do you think about this idea?

**Comment by Rendanic** [comment]
Here is an example how it works with Clusterware/Oracle Restart. It doesn't look like a really nice solution but it is working in the current `oradb-create` role. One problem was, that the role `oradb-create` doesn't know where GI/Restart is installed. I get that information from `/etc/oracle/olr.loc` which is existing in 11.2+.

```
  - name: Check if database is already created (2)
    shell: ". /etc/oracle/olr.loc ;${crs_home}/bin/srvctl config database -d {{ item.oracle_db_name }} > /dev/null ; if [ $? -eq 0 ] ; then echo '1' ; else echo '0' ; fi"
    with_items: oracle_databases
    when: item.oracle_db_name is defined and oracle_install_option_gi in ('CRS_CONFIG','HA_CONFIG')
    tags:
    - checkifdbexists
    register: checkdbexist

```
