### ISSUE TITLE
Problem to install one-off patches with oraswdb-manage-patches

### ISSUE THREAD

**Issue by duhlig** [oravirt/ansible-oracle#178]
Issue type: Request for assistance
Priority: medium
Affected files:
  - ansible-oracle/roles/oraswdb-manage-patches/tasks/db-home-patch.yml
  - ansible-oracle/roles/oraswdb-manage-patches/tasks/unpack-files.yml

Steps to reproduce the issue:

  - The remote stage is permanently mounted to /stage on all of our Linux servers. As the files in stage for historical reasons are ordered differently to ansible-oracle's fashion I created a sub-directory _symlinks_for_ansible (self-explaining). I think I don't need to copy the files but unpack as requested by the roles.

  - set group_vars like this:

```yaml
      oracle_version_db: 12.1.0.2
      oracle_edition_db: EE
      oracle_sw_source_local: /stage
      oracle_stage_remote: /stage/_symlinks_for_ansible
      oracle_sw_copy: False
      oracle_sw_unpack: True
    
      db_homes_config:
        12102-EC:
          home: "{{ oracle_edition_db|lower }}"
          version: "{{ oracle_version_db }}"
          edition: "{{ oracle_edition_db|upper }}"
          opatch_minversion: 12.2.0.1.16
          opatchauto:
            - patchid: 28729169
              patchversion: 12.1.0.2.190115
              state: present
              subpatches:
                - 19769480
                - 20299023
                - 20831110
                - 21359755
                - 21948354
                - 22291127
                - 23054246
                - 24006101
                - 24732082
                - 25171037
                - 25755742
                - 26609783
                - 26713565
                - 26925311
                - 27338041
                - 27547329
                - 28259833
                - 28729169
          opatch:
            - patchid: 27015449
              state: present
              path: p27015449_121020_Linux-x86-64.zip
            - patchid: 18352930
              state: present
              path: p18352930_121020_Generic.zip
            - patchid: 18881811
              state: present
              path: p18881811_121020_Generic.zip
```
  

- run ansible-playbook and "call" role oraswdb-manage-patches

Problem description:

  opatchauto works as expected but opatch throws this error:

    OPatch failed with error code 135
    STDERR: Argument(s) Error... Patch Location not valid
    COMMAND: /u01/app/oracle/12.1.0.2/ee/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -ph /u01/stage/patches/12.1.0.2/p27015449_121020_Linux-x86-64.zip/ -oh /u01/app/oracle/12.1.0.2/ee"

  Seemingly obvious: OPatch doesn't need unpacked files, and I didn't request ansible to transfer them from oracle_stage_remote to oracle_patch_install. So I understand that unpack-files.yml only unpacks the files for opatchauto.

  Question: How to do it right? Should OPatch use oracle_stage_remote in some cases or did I miss the step (which one) to copy the zip files of the one-off patches?

Kind regards,
Dietmar

**Comment by oravirt** [comment]
Hi - I'll look into it

**Comment by Rendanic** [comment]
The variable definition looks wrong for me:
`path: p27015449_121020_Linux-x86-64.zip`
This is the archive of the patch but a path to the location of the extracted archive is needed.

The error shows where opatch is searching for the patch:
`-ph /u01/stage/patches/12.1.0.2/p27015449_121020_Linux-x86-64.zip/`

**Comment by oravirt** [comment]
> The error shows where opatch is searching for the patch:
> -ph /u01/stage/patches/12.1.0.2/p27015449_121020_Linux-x86-64.zip/

yes, and that is one part of the problem, the other is that there is no unarchive task for one-off patches (I have a fix for that, soon to be pushed).

I'll push the fix and show an example of a working configuration

**Comment by duhlig** [comment]
Hi Mikael, Thorsten,

thanks for your help. This is a system with software-only GI and single-instance, non-CDB database.

In fact OPatch doesn't need to get one-off patches extracted:

```
$ /u01/app/oracle/12.1.0.2/ee/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -ph /stage/_symlinks_for_ansible/patches/12.1.0.2/p27015449_121020_Linux-x86-64.zip -oh /u01/app/oracle/12.1.0.2/ee
Oracle Interim Patch Installer version 12.2.0.1.16
Copyright (c) 2019, Oracle Corporation.  All rights reserved.

PREREQ session

Oracle Home       : /u01/app/oracle/12.1.0.2/ee
Central Inventory : /u01/app/oraInventory
   from           : /u01/app/oracle/12.1.0.2/ee/oraInst.loc
OPatch version    : 12.2.0.1.16
OUI version       : 12.1.0.2.0
Log file location : /u01/app/oracle/12.1.0.2/ee/cfgtoollogs/opatch/opatch2019-05-09_08-27-32AM_1.log

Invoking prereq "checkconflictagainstohwithdetail"

Prereq "checkConflictAgainstOHWithDetail" passed.

OPatch succeeded.
```

You or perhaps I will find my mistake, but I didn't get the "philosophy" behind ansible-oracle's way of one-off patch apply.

Kind Regards,
Dietmar

**Comment by oravirt** [comment]
> In fact OPatch doesn't need to get one-off patches extracted:

Yes, but I want to treat all patches the same, it's way to much work to cater to every possible way of dealing with patching in Oracle (which is a horrible experience already)

So if you just remove the path everything should work (it still has to be added to the `oracle_sw_patches` list though

```
db_homes_config:
        12102-EC:
          home: "{{ oracle_edition_db|lower }}"
          version: "{{ oracle_version_db }}"
          edition: "{{ oracle_edition_db|upper }}"
          opatch_minversion: 12.2.0.1.16
          opatchauto:
            - patchid: 28729169
              patchversion: 12.1.0.2.190115
              state: present
              subpatches:
                - 19769480
                - 20299023
                - 20831110
                - 21359755
                - 21948354
                - 22291127
                - 23054246
                - 24006101
                - 24732082
                - 25171037
                - 25755742
                - 26609783
                - 26713565
                - 26925311
                - 27338041
                - 27547329
                - 28259833
                - 28729169
          opatch:
            - patchid: 27015449
              state: present
            - patchid: 18352930
              state: present
            - patchid: 18881811
              state: present

```

And for reference: 
 `oracle_sw_source_local: /stage `     <--- This is the directory on the Ansible controlmachine where the .zip files are located. Used when files are being copied from the controlmachine to the db nodes (`is_sw_source_local: True`)
