### ISSUE TITLE
Can’t use oraasm-manage-diskgroups to create DG

### ISSUE THREAD

**Issue by tanshaolong** [oravirt/ansible-oracle#189]
Hello,

I use oraasm-manage-diskgroups to create dg for oracle 11.2.0.4, meet below error message, but it is ok if I use oraasm-createdg to create DG with same configuration.

The error message:
```
The full traceback is:
  File "/tmp/ansible_0QghJ6/ansible_module_oracle_asmdg.py", line 405, in main
    conn = cx_Oracle.connect(user, password, dsn, mode=cx_Oracle.SYSASM)

failed: [rac1] (item={u'attributes': [{u'name': u'compatible.asm', u'value': u'11.2.0.4.0'}, {u'name': u'compatible.rdbms', u'value': u'11.2.0.4.0'}], u'state': u'present', u'disk': [{u'device': u'/dev/sde', u'asmlabel': u'fra01'}], u'diskgroup': u'fra', u'properties': [{u'redundancy': u'external', u'ausize': 4}]}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attribute_name": [
                "compatible.asm", 
                "compatible.rdbms"
            ], 
            "attribute_value": [
                "11.2.0.4.0", 
                "11.2.0.4.0"
            ], 
            "disks": [
                "ORCL:FRA01"
            ], 
            "host": "rac1", 
            "hostname": "rac1", 
            "name": "fra", 
            "oh": "/u01/app/grid/product/11.2.0.4/grid", 
            "oracle_home": "/u01/app/grid/product/11.2.0.4/grid", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": "1521", 
            "pw": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "redundancy": "external", 
            "service_name": "+ASM", 
            "sn": "+ASM", 
            "state": "present", 
            "un": "sys", 
            "user": "sys"
        }
    }, 
    "item": {
        "attributes": [
            {
                "name": "compatible.asm", 
                "value": "11.2.0.4.0"
            }, 
            {
                "name": "compatible.rdbms", 
                "value": "11.2.0.4.0"
            }
        ], 
        "disk": [
            {
                "asmlabel": "fra01", 
                "device": "/dev/sde"
            }
        ], 
        "diskgroup": "fra", 
        "properties": [
            {
                "ausize": 4, 
                "redundancy": "external"
            }
        ], 
        "state": "present"
    }, 
    "msg": "Could not connect to ASM: ORA-12541: TNS:no listener, connect descriptor: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rac1)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=+ASM))), username: sys, pass: ********"
}
```

Below is my configuration for DG.
```
asm_diskgroups:
  - diskgroup: crs
    state: present
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.asm, value: "{{ oracle_install_version_gi }}.0"}
      - {name: compatible.rdbms, value: 11.2.0.4.0}
    disk:
      - {device: /dev/sdc, asmlabel: crs01}
  - diskgroup: data
    state: present
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.asm, value: "{{ oracle_install_version_gi }}.0"}
      - {name: compatible.rdbms, value: 11.2.0.4.0}
    disk:
      - {device: /dev/sdd, asmlabel: data01}
      #- {device: /dev/sdg, asmlabel: data02}
  - diskgroup: fra
    state: present
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.asm, value: "{{ oracle_install_version_gi }}.0"}
      - {name: compatible.rdbms, value: 11.2.0.4.0}
    disk:
      - {device: /dev/sde, asmlabel: fra01}
```

Which wrong is for my configuration? Thanks
