### ISSUE TITLE
Unable to install 11.2.0.4/12.1.0.2 database using single-instance-db-on-fs.yml

### ISSUE THREAD

**Issue by singlatk** [oravirt/ansible-oracle#196]
ansible-playbook single-instance-db-on-fs.yml 

Returns following error -
- TASK [oraswdb-install : install-home-db | Install Oracle Database Server] *********************************************************************************************************
fatal: [ansible2]: FAILED! => {"changed": true, "cmd": "/u01/app/oracle/18.3.0.0/db1-base/runInstaller -responseFile /u01/stage/rsp/18300-base_ansible2.rsp -ignorePrereq -silent -waitforcompletion", "delta": "0:00:00.012639", "end": "2019-12-14 20:20:51.478126", "failed_when_result": true, "msg": "non-zero return code", "rc": 127, "start": "2019-12-14 20:20:51.465487", "stderr": "/bin/sh: /u01/app/oracle/18.3.0.0/db1-base/runInstaller: No such file or directory", "stderr_lines": ["/bin/sh: /u01/app/oracle/18.3.0.0/db1-base/runInstaller: No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************************************************ansible2                   : ok=50   changed=3    unreachable=0    failed=1    skipped=33   rescued=0    ignored=1

#######################################################################
Please can you advise which files requires ammending and with what? And if possible, please can you upload the ammended file?  From the issue list, I can see that two other people have faced similar issue but fix suggested haven't worked for me, may be my limited programming knowledge. 
Appreciate you help, thanks again.

**Comment by oravirt** [comment]
Hi,
Which are the other issues you are referring to?

I suggest you have a look at `group_vars/vbox-*` (I guess `group_vars/vbox-si-fs`) in your case.
They are the most up to date example configurations that should work for most cases.

The playbook `single-instance-db-on-fs.yml` (obviously) needs a configuration to use, so what does your configuration look like? How do you call the playbook?

In short, in order for the ORACLE_HOME to be installed you need to fix these 2 variables:
```
db_homes_config:
  12102-base: <-- This key is referenced in db_homes_installed.home
    home: db1-base
    version: 12.1.0.2 <-- Version to be installed
    edition: EE
  18300-base: <-- This key is referenced in db_homes_installed.home
    home: db1-base
    version: 18.3.0.0 <-- Version to be installed
    edition: EE
```

```
db_homes_installed:
     - home: 12102-base <-- This is the key referenced in db_homes_config
       apply_patches: False
       state: present
    - home: 18300-base <-- This is the key referenced in db_homes_config
       apply_patches: False
        state: present
```
And then, when you're ready to create a cdb/pdb, the `home` key references the key in oracle_databases/oracle_pdbs decides the ORACLE_HOME where the DB will run

```
oracle_databases:
      - home: 12102-base  
         ....
oracle_pdbs:
      - home: 12102-base  
```

So,
`db_homes_config:` This is where the individual ORACLE_HOMES are defined
`db_homes_installed:` This is where you choose which homes from `db_homes_config` you want to install

**Comment by singlatk** [comment]
Hi Mikael,

Thank you for your response.

group_vars/vbox-si-fs has databases.yml, db-homes.yml and few ohrer files. Seems like I need to update databases.yml, db-homes.yml  and set the values to 12.1.0.2 ?

When you say “The playbook single-instance-db-on-fs.yml (obviously) needs a configuration to use”, Is there a document available suggesting how to use these playbooks? I just ran ‘single-instance-db-on-fs.yml  ‘playbook as per README 
i.e. ansible-playbook single-instance-db-on-fs.yml -e hostgroup=myhostgroup -i /path/to/inventory
and uploaded software on /tmp

Regards

**Comment by singlatk** [comment]
[db-homesANDdatabase.zip](https://github.com/oravirt/ansible-oracle/files/3965381/db-homesANDdatabase.zip)

See attached two files in zip format a) databases.yml b) db-homes.yml in which I made changes suggested by you and run playbook

ansible-playbook single-instance-db-on-fs.yml -e hostgroup=dbserver -i /etc/ansible/hosts

but still got the same error 

TASK [oraswdb-install : install-home-db | Install Oracle Database Server] *******************************************************************************************************************************************************************
fatal: [ansible2]: FAILED! => {"changed": true, "cmd": "/u01/app/oracle/18.3.0.0/db1-base/runInstaller -responseFile /u01/stage/rsp/18300-base_ansible2.rsp -ignorePrereq -silent -waitforcompletion", "delta": "0:00:00.008768", "end": "2019-12-15 19:41:32.981883", "failed_when_result": true, "msg": "non-zero return code", "rc": 127, "start": "2019-12-15 19:41:32.973115", "stderr": "/bin/sh: /u01/app/oracle/18.3.0.0/db1-base/runInstaller: No such file or directory", "stderr_lines": ["/bin/sh: /u01/app/oracle/18.3.0.0/db1-base/runInstaller: No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
ansible2                   : ok=50   changed=3    unreachable=0    failed=1    skipped=33   rescued=0    ignored=1


Any help given will be apperciated ! Thanks

**Comment by singlatk** [comment]
Dear oravit, 
Any further updates for me on the issue, please?  To me it looks like changes made in a) databases.yml b) db-homes.yml are not being reflected which is why is why single-instance-db-on-fs.yml is still referencing to 18300.

Do I need to update single-instance-db-on-fs.yml and include group_vars ? if so, please can you advise?

For your convineince, I am pasting the error message again

================================================================
TASK [oraswdb-install : install-home-db | Extract files (from remote location)] *********************************************************************************************************************
skipping: [ansible2] => (item=[{u'creates': u'database/stage/sizes/oracle.server.Custom.sizes.properties', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_database_1of2.zip'}, {u'home': u'ly_patches': False}])
skipping: [ansible2] => (item=[{u'creates': u'database/stage/sizes/oracle.server.Custom.sizes.properties', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_database_1of2.zip'}, {u'home': u'y_patches': False}])
skipping: [ansible2] => (item=[{u'creates': u'database/stage/sizes/oracle.server.Custom.sizes.properties', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_database_1of2.zip'}, {u'home': u'ply_patches': True}])
skipping: [ansible2] => (item=[{u'creates': u'database/install/.oui', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_database_2of2.zip'}, {u'home': u'18300-base', u'state': u'present', u'
skipping: [ansible2] => (item=[{u'creates': u'database/install/.oui', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_database_2of2.zip'}, {u'home': u'12201-base', u'state': u'absent', u'a
skipping: [ansible2] => (item=[{u'creates': u'database/install/.oui', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_database_2of2.zip'}, {u'home': u'12201-180717', u'state': u'absent', u

TASK [oraswdb-install : install-home-db | Install Oracle Database Server] ***************************************************************************************************************************
fatal: [ansible2]: FAILED! => {"changed": true, "cmd": "/u01/app/oracle/18.3.0.0/db1-base/runInstaller -responseFile /u01/stage/rsp/18300-base_ansible2.rsp -ignorePrereq -silent -waitforcompletion"9-12-15 20:04:24.813743", "failed_when_result": true, "msg": "non-zero return code", "rc": 127, "start": "2019-12-15 20:04:24.805734", "stderr": "/bin/sh: /u01/app/oracle/18.3.0.0/db1-base/runInstar_lines": ["/bin/sh: /u01/app/oracle/18.3.0.0/db1-base/runInstaller: No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP ******************************************************************************************************************************************************************************************
ansible2                   : ok=50   changed=3    unreachable=0    failed=1    skipped=33   rescued=0    ignored=1


================================================================
Thanks

**Comment by oravirt** [comment]
> [db-homesANDdatabase.zip](https://github.com/oravirt/ansible-oracle/files/3965381/db-homesANDdatabase.zip)
> 
db-homes.yml seems to be correct, 
```

db_homes_config:
    12201-base:
     home: db1-base
     version: 12.2.0.1
     edition: EE

db_homes_installed:
       - home: 12201-base
        apply_patches: False
        state: present

```
but databases.yml needs a change.
You're referencing the wrong home:
```
oracle_databases:
  - home: db1 <-- this should be 12201-base
```
