### ISSUE TITLE
dbhome path/version

### ISSUE THREAD

**Issue by stelb** [oravirt/ansible-oracle#226]
As Oracle changed it's version numbering and i can't even install e.g. 19.8 directly it does not make sense to install into 19.3.0.0 directory. After RU apply it's not 19.3 anymore.
It i think version and directory should be only 19

```
db_homes_config:
  19-base:
    home: db1
    version: 19
    edition: EE
```
installing 19.3.0.0 into /u01/app/oracle/product/19/db1
