### ISSUE TITLE
ocenv with no dbca/manage-db tasks

### ISSUE THREAD

**Issue by talek** [oravirt/ansible-oracle#341]
Hello,

I'm starting to really like ocenv tool and I consider deploying it on our Oracle servers. These databases are registered in our ansible inventory (minimal info), but they haven't been created using `oradb-manage-db` role. We're using `ansible-oracle` for patching only. Now, I'm looking for a risk-free way to deploy ocenv without touching any running DBs... So, I'd like to avoid running manage-db tasks which may cause instance restarts or other side effects. Using ansible tags doesn't seem to work since those tasks are tagged in a way which prohibits the filtering I'd like to achieve. Do you have any advice on how to properly handle this? Would it be a good idea to create a separate role just for ocenv deployment/upgrade (breaking change)?

Thank you!
Alec

**Comment by Rendanic** [comment]
You could create a dedicated playbook or include the task in your play:

```
---
- name: Database Server Database Creation
  hosts: "{{ hostgroup | default('all') }}"
  any_errors_fatal: true
  become: true
  become_user: oracle
  tasks:
    - name: Install ocenv
      ansible.builtin.include_role:
        name: opitzconsulting.ansible_oracle.oradb_manage_db
        tasks_from: ocenv.yml
```

This will install the `ocenv` only - without any other stuff from `oradb_manage_db`.
