### ISSUE TITLE
Setting similar oracle_db_name for multiple dbs results in bad .profile

### ISSUE THREAD

**Issue by chrisbrookes** [oravirt/ansible-oracle#35]
If you have mulitple dbs and their names clash in a grep, e.g.:
```
oracle_databases: 
  - home: db1    
    oracle_db_name: orcl
# ...
  - home: db1    
    oracle_db_name: orcl2
```
The oradb-create _Add dotprofile (1)_ task which basically greps for existing running dbs gets 
```
orcl2
orcl
```
for the orcl db when it should only get `orcl`. This results in the .profile_orlc being badly formed around the `ORACLE_SID` bit.
Workaround is to not have clashing names (orcl1 & orcl2 instead of orcl & orcl2), so not a huge issue.
Fix is to amend the grep to use the -w flag.
