### ISSUE TITLE
Undefined variable 'listener_home_config' on v4.2.0

### ISSUE THREAD

**Issue by djvl3it** [oravirt/ansible-oracle#385]
Hi, I was happy to see support for EL9 is being worked on and while I know this is experimental I decided to give the most recent beta release (v4.2.0) a try on a test machine. Deployment went well until the following error showed:

```
TASK [opitzconsulting.ansible_oracle.oradb_manage_db : tnsnames.ora | create IFILE entry in tnsnames.ora] ***
fatal: [torad011.test.vu.nl]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {%- if db_homes_config[_oradb_manage_db_tns_loop_helper.home]['readonly_home'] | default(false) %}
{{ oracle_base }}/homes/{{ db_homes_config[_oradb_manage_db_tns_loop_helper.home]['oracle_home_name'] }}
{%- else %}{{ listener_home_config }}{% endif -%}: 'listener_home_config' is undefined. 'listener_home_config' is undefined. {%- if db_homes_config[_oradb_manage_db_tns_loop_helper.home]['readonly_home'] | default(false) %}
{{ oracle_base }}/homes/{{ db_homes_config[_oradb_manage_db_tns_loop_helper.home]['oracle_home_name'] }}
{%- else %}{{ listener_home_config }}{% endif -%}: 'listener_home_config' is undefined. 'listener_home_config' is undefined

The error appears to be in '/runner/project/collections/ansible_collections/opitzconsulting/ansible_oracle/roles/oradb_manage_db/tasks/tnsnames.yml': line 6, column 3, but may be elsewhere in the file depending on the exact syntax problem.
```
I have not tried to set the var myself, thought let's report the issue first.

**Comment by Rendanic** [comment]
I thik it's a bug.

Could you paste `oracle_listeners_config` and `listener_installed` for easier testing?

**Comment by djvl3it** [comment]
Sure, I am using the following:

````
oracle_listeners_config:
  LISTENER:
    home: 19300-base
    address:
      - host: "{{ansible_hostname}}"
        protocol: TCP
        port: 1521

listener_installed:
  - home: 19300-base
    listener_name: LISTENER
    state: present
````
