### ISSUE TITLE
configuge_hugepages does not work anymore

### ISSUE THREAD

**Issue by bartowl** [oravirt/ansible-oracle#410]
`configure_hugepages` does not disable the task in orahost/tasks/main.yml:370 and in effect it sets huge pages to 0 regardless of previous value even when having this boolean set to false. (missing when condition at task)
Temporary workaround is to redefine `oracle_hugepages` with empty list

**Comment by Rendanic** [comment]
Hi Bartek,
this bug is not new in 4.x. It is broken in 3.x as well:

https://github.com/oravirt/ansible-oracle/blob/release/3.x/roles/orahost/tasks/main.yml
```
- name: Oracle hugepages
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items: "{{ oracle_hugepages }}"
  register: systclcmd
  tags: sysctl,hugepages
```

```
configure_hugepages: true
configure_hugepages_by: memory              # percentage/memory
percent_hugepages: 50                       # Percentage (0-100) of total RAM to dedicate to hugepages, Configures vm.nr_hugepages
size_in_gb_hugepages: 1                     # The amount of RAM in GB to dedicate to hugepages
nr_hugepages_percent: "{{ ((((percent_hugepages / 100) * ansible_memtotal_mb) / 2) + 2) | round | int }}"
nr_hugepages_memory: "{{ (((size_in_gb_hugepages * 1024) / 2) + 2) | round | int }}"
nr_hugepages: "{% if configure_hugepages %}\
                 {%- if configure_hugepages_by | lower == 'percentage' %}{{ nr_hugepages_percent }}\
                 {%- elif configure_hugepages_by | lower == 'memory' %}{{ nr_hugepages_memory }}\
                 {%- endif %}\
                 {%- else %}0\
               {%- endif %}"
```

`nr_hugepages` is always 0 when `configure_hugepages` is `false`. That has not been changed in 4.x


In Release 4.x:
https://github.com/oravirt/ansible-oracle/blob/v4.4.2/roles/orahost/tasks/main.yml
```
- name: Oracle hugepages
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    ignoreerrors: true
  with_items: "{{ oracle_hugepages }}"
  register: systclcmd
  tags: sysctl,hugepages,molecule-idempotence-notest
```

```
configure_hugepages: true
configure_hugepages_by: memory
nr_hugepages: "{% if configure_hugepages %}\
                 {%- if configure_hugepages_by | lower == 'percentage' %}{{ nr_hugepages_percent }}\
                 {%- elif configure_hugepages_by | lower == 'memory' %}{{ nr_hugepages_memory }}\
                 {%- endif %}\
                 {%- else %}0\
               {%- endif %}"
```
