### ISSUE TITLE
roles/oraswgi_install/tasks/assert.yml fails on empty default_gipass, even if sysasmpassword/asmmonitorpassword are set

### ISSUE THREAD

**Issue by ThiloSolbrig** [oravirt/ansible-oracle#428]
```yaml
- name: Oraswgi_install | Assert variables
  ansible.builtin.assert:
    quiet: true
    that:
      - default_gipass | length > 0
      - oracle_install_version_gi is defined
      - oracle_gi_cluster_type in ('STANDARD', 'STANDALONE')
  tags: always
```
asserts default_gipass was set. default_gipass doesn't need to be mandatory if sysasmpassword and asmmonitorpassword are set instead.
