### ISSUE TITLE
become doesn't work if ansible_user is other than root

### ISSUE THREAD

**Issue by ThiloSolbrig** [oravirt/ansible-oracle#429]
sudoers file is missing policies to enable ansible_user to become oracle / grid. This becomes an issue if ansible doesn't connect as root but any other user. Going to provide a fix to include those policies in roles/orahost/templates/sudoers.j2

**Comment by Rendanic** [comment]
The configuration for sudo for oracle has been disabled (`configure_oracle_sudo=false`) by default, because the user gain full root rights on the system.

There is an issue with the task, when `role_separation=true and configure_oracle_sudo=true` is used.

```
- name: User | Add Oracle user to sudoers
  ansible.builtin.template:
    src: "{{ sudoers_template }}"
    dest: "/etc/sudoers.d/{{ item.username }}"
    owner: root
    mode: 0440
  with_items: "{{ oracle_users }}"
  when:
    - configure_oracle_sudo
  tags:
    - sudoadd
```

`oracle` is added to sudoers but `grid` is missing.

Is this the issue you have in your environment?
