### ISSUE TITLE
oraswgi-opatch

### ISSUE THREAD

**Issue by oravirt** [oravirt/ansible-oracle#72]
It should be possible to specify which 'opatchauto' patch (and potentially one-off's) should be applied to a specific system.

So I'm thinking something like this.

```
gi_patches:
         opatchauto:
                 - some_opatchauto_identifier
         oneoff:
                 - some_oneoff_identifier
                 - some_oneoff_identifier
```
         
where 'some-*_identifier' either maps to an existing construct (`oracle_sw_image_gi_psu`) or something new.
