### ISSUE TITLE
Filesystem Provision

### ISSUE THREAD

**Issue by akerrai** [oravirt/ansible-oracle#74]
Please forgive me for any stupidness.  Having never worked with Ansible before I'm muddling my way through this.

I'm trying to follow the single instance install (ASM) but seem to be failing at the filesystem stage.

I keep hitting the below, having tried to fudge around it I'm not entirely sure what it is I'm missing:

TASK [orahost : filesystem | Create directories] ********************************************************************************************************************************************************************************************
fatal: [os-dat-ans-tst-01.local]: FAILED! => {"msg": "could not find 'filesystem' key in iterated item '{u'device': u'/dev/xvdc', u'mntp': u'/u01', u'vgname': u'vgora', u'pvname': u'/dev/xvdc1', u'lvname': u'lvora'}'"}
        to retry, use: --limit @/root/ansible-oracle/single-instance-db-on-asm.retry

**Comment by oravirt** [comment]
Hi!
It would help if you could paste your entire config (i.e `group_vars/your-config-name`), or at least the host_fs_layout (it should look something like this):
```
 host_fs_layout:
   - vgname: vgora
     state: present
     filesystem:
       - {mntp: /u01, lvname: lvora, lvsize: 100%FREE, fstype: ext4}
     disk:
       - {device: /dev/sdb, pvname: /dev/sdb1}
```
Judging by the error, it looks like the filesystem key is missing.
